### ISSUE TITLE
大佬！运行错误！  facechain 微信群二维码过期了

### ISSUE THREAD

**Issue by windy117** [THtianhao/ComfyUI-FaceChain#9]
大佬！ facechain 微信群二维码过期了

Error occurred when executing FC FaceDetectCrop:

FaceDetectionPipeline: DamoFdDetect: DLL load failed while importing _ext: 找不到指定的程序。

File "F:\ComfyUI\execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "F:\ComfyUI\execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "F:\ComfyUI\execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "F:\ComfyUI\custom_nodes\ComfyUI-FaceChain\facechain\nodes.py", line 45, in face_detection
corp_img_pil, mask, bbox, points_array = facechain_detect_crop(pil_image, face_index, crop_ratio, mode)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "F:\ComfyUI\custom_nodes\ComfyUI-FaceChain\facechain\common\model_processor.py", line 13, in facechain_detect_crop
det_result = get_face_detection()(source_image_pil)
^^^^^^^^^^^^^^^^^^^^
File "F:\ComfyUI\custom_nodes\ComfyUI-FaceChain\facechain\model_holder.py", line 23, in get_face_detection
face_detection = pipeline(task=Tasks.face_detection, model='damo/cv_ddsar_face-detection_iclr23-damofd', model_revision='v1.1')
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "F:\ComfyUI\.ext\Lib\site-packages\modelscope\pipelines\builder.py", line 170, in pipeline
return build_pipeline(cfg, task_name=task)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "F:\ComfyUI\.ext\Lib\site-packages\modelscope\pipelines\builder.py", line 65, in build_pipeline
return build_from_cfg(
^^^^^^^^^^^^^^^
File "F:\ComfyUI\.ext\Lib\site-packages\modelscope\utils\registry.py", line 215, in build_from_cfg
raise type(e)(f'{obj_cls.__name__}: {e}')

!!! Exception during processing!!! FaceDetectionPipeline: DamoFdDetect: DLL load failed while importing _ext: 找不到指定的程序。
Traceback (most recent call last):
  File "F:\ComfyUI\.ext\Lib\site-packages\modelscope\utils\registry.py", line 210, in build_from_cfg
    return obj_cls._instantiate(**args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI\.ext\Lib\site-packages\modelscope\models\base\base_model.py", line 67, in _instantiate
    return cls(**kwargs)
           ^^^^^^^^^^^^^
  File "F:\ComfyUI\.ext\Lib\site-packages\modelscope\models\cv\face_detection\scrfd\damofd_detect.py", line 31, in __init__
    super().__init__(model_dir, **kwargs)
  File "F:\ComfyUI\.ext\Lib\site-packages\modelscope\models\cv\face_detection\scrfd\scrfd_detect.py", line 36, in __init__
    from mmdet.models import build_detector
  File "F:\ComfyUI\.ext\Lib\site-packages\mmdet\models\__init__.py", line 2, in <module>
    from .backbones import *  # noqa: F401,F403
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI\.ext\Lib\site-packages\mmdet\models\backbones\__init__.py", line 2, in <module>
    from .csp_darknet import CSPDarknet
  File "F:\ComfyUI\.ext\Lib\site-packages\mmdet\models\backbones\csp_darknet.py", line 11, in <module>
    from ..utils import CSPLayer
  File "F:\ComfyUI\.ext\Lib\site-packages\mmdet\models\utils\__init__.py", line 13, in <module>
    from .point_sample import (get_uncertain_point_coords_with_randomness,
  File "F:\ComfyUI\.ext\Lib\site-packages\mmdet\models\utils\point_sample.py", line 3, in <module>
    from mmcv.ops import point_sample
  File "F:\ComfyUI\.ext\Lib\site-packages\mmcv\ops\__init__.py", line 3, in <module>
    from .active_rotated_filter import active_rotated_filter
  File "F:\ComfyUI\.ext\Lib\site-packages\mmcv\ops\active_rotated_filter.py", line 10, in <module>
    ext_module = ext_loader.load_ext(
                 ^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI\.ext\Lib\site-packages\mmcv\utils\ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI\.ext\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: DLL load failed while importing _ext: 找不到指定的程序。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\ComfyUI\.ext\Lib\site-packages\modelscope\utils\registry.py", line 212, in build_from_cfg
    return obj_cls(**args)
           ^^^^^^^^^^^^^^^
  File "F:\ComfyUI\.ext\Lib\site-packages\modelscope\pipelines\cv\face_detection_pipeline.py", line 36, in __init__
    super().__init__(model=model, **kwargs)
  File "F:\ComfyUI\.ext\Lib\site-packages\modelscope\pipelines\base.py", line 100, in __init__
    self.model = self.initiate_single_model(model, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI\.ext\Lib\site-packages\modelscope\pipelines\base.py", line 53, in initiate_single_model
    return Model.from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI\.ext\Lib\site-packages\modelscope\models\base\base_model.py", line 183, in from_pretrained
    model = build_model(model_cfg, task_name=task_name)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI\.ext\Lib\site-packages\modelscope\models\builder.py", line 35, in build_model
    model = build_from_cfg(
            ^^^^^^^^^^^^^^^
  File "F:\ComfyUI\.ext\Lib\site-packages\modelscope\utils\registry.py", line 215, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
ImportError: DamoFdDetect: DLL load failed while importing _ext: 找不到指定的程序。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI\custom_nodes\ComfyUI-FaceChain\facechain\nodes.py", line 45, in face_detection
    corp_img_pil, mask, bbox, points_array = facechain_detect_crop(pil_image, face_index, crop_ratio, mode)
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI\custom_nodes\ComfyUI-FaceChain\facechain\common\model_processor.py", line 13, in facechain_detect_crop
    det_result = get_face_detection()(source_image_pil)
                 ^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI\custom_nodes\ComfyUI-FaceChain\facechain\model_holder.py", line 23, in get_face_detection
    face_detection = pipeline(task=Tasks.face_detection, model='damo/cv_ddsar_face-detection_iclr23-damofd', model_revision='v1.1')
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI\.ext\Lib\site-packages\modelscope\pipelines\builder.py", line 170, in pipeline
    return build_pipeline(cfg, task_name=task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI\.ext\Lib\site-packages\modelscope\pipelines\builder.py", line 65, in build_pipeline
    return build_from_cfg(
           ^^^^^^^^^^^^^^^
  File "F:\ComfyUI\.ext\Lib\site-packages\modelscope\utils\registry.py", line 215, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
ImportError: FaceDetectionPipeline: DamoFdDetect: DLL load failed while importing _ext: 找不到指定的程序。

[rgthree] Using rgthree's optimized recursive execution.
2024-05-22 09:39:50,529 - modelscope - INFO - Use user-specified model revision: v1.1
2024-05-22 09:39:50,826 - modelscope - INFO - initiate model from F:\ComfyUI\.cache\modelscope\hub\damo\cv_ddsar_face-detection_iclr23-damofd
2024-05-22 09:39:50,827 - modelscope - INFO - initiate model from location F:\ComfyUI\.cache\modelscope\hub\damo\cv_ddsar_face-detection_iclr23-damofd.
2024-05-22 09:39:50,892 - modelscope - INFO - initialize model from F:\ComfyUI\.cache\modelscope\hub\damo\cv_ddsar_face-detection_iclr23-damofd

**Comment by THtianhao** [comment]
ok

**Comment by THtianhao** [comment]
已经更新
